{
 "title": "Heatlh Assistant Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Hourly Health Assistant App Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour', timestamp) as hour, count(distinct id) FROM conversations GROUP BY 1"
    }
   ]
  },
  {
   "title": "Average Health Assistant App User Feedback Score",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(feedback) from feedback "
    }
   ]
  },
  {
   "title": "Count of LLM answers by relevance (evaluated by LLM)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT relevance, COUNT(*) \nFROM conversations \nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Hourly OpenAI cost",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select date_trunc('hour', timestamp) as hour,\n       sum(openai_cost) over (partition by date_trunc('hour', timestamp)) as openai_cost\nfrom conversations;"
    }
   ]
  },
  {
   "title": "Cumulative Sum of OpenAI Tokens Processed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select date_trunc('hour', timestamp) as hour,\n       SUM(total_tokens) OVER (ORDER BY timestamp ROWS UNBOUNDED PRECEDING) as cumulative_sum_tokens\nfrom conversations"
    }
   ]
  }
 ]
}